### ISSUE TITLE
error when predicting new image

### ISSUE THREAD

**Issue by BackT0TheFuture** [xinghedyc/mxnet-cnn-lstm-ctc-ocr#4]
> ('seq_len : ', 100)
('seq_len : ', 100)
[02:42:42] e:\work\testroot\mxnet\src\operator\./cudnn_algoreg-inl.h:106: Runnin
g performance tests to find the best convolution algorithm, this can take a whil
e... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
('seq_len : ', 20L)
Traceback (most recent call last):
  File "predict.py", line 128, in <module>
    model.forward(data_batch, is_train=False)
  File "D:\Anaconda2\lib\site-packages\mxnet-0.11.1-py2.7.egg\mxnet\module\bucke
ting_module.py", line 420, in forward
    data_batch.provide_label)
  File "D:\Anaconda2\lib\site-packages\mxnet-0.11.1-py2.7.egg\mxnet\module\bucke
ting_module.py", line 347, in switch_bucket
    symbol, data_names, label_names = self._sym_gen(bucket_key)
  File "predict.py", line 87, in sym_gen
    num_label=25, dropout=0.5), ('data', 'l0_init_c', 'l1_init_c', 'l0_init_h',
'l1_init_h'), (
  File "D:\DeepLearning\MXNET\example\mxnet-cnn-lstm-ctc-ocr\text_lstm.py", line
 156, in bi_lstm_unroll
    hidden =mx.sym.Flatten(data=column_features[k])
  File "D:\Anaconda2\lib\site-packages\mxnet-0.11.1-py2.7.egg\mxnet\symbol\symbo
l.py", line 511, in __getitem__
    raise TypeError('Symbol only support integer index to fetch i-th output')
TypeError: Symbol only support integer index to fetch i-th output

how to handle this ?
thx!

**Comment by xinghedyc** [comment]
The code has been tested under mxnet 0.9.4 on ubuntu. The newest mxnet may be incompatible.
Do you train the model successfully?

**Comment by BackT0TheFuture** [comment]
@xinghedyc  
yes, model was trained successfully,  train accuracy is 1.000000 but validation accuracy is only 0.114583 after 1000 epochs. I run the code on windows8.1 64bit  mxnet 0.11rc3
![20170906015045](https://user-images.githubusercontent.com/10088733/30074999-21261aa4-92a6-11e7-8ca9-303c54b4a067.png)

**Comment by xinghedyc** [comment]
I can run this predict.py successfully on my server like
![59b94d4d-a341-415b-9e03-a071793b7771](https://user-images.githubusercontent.com/9301248/30210634-e497273c-94cf-11e7-81b0-181f938ca095.png)
, I changed num_label in predict.py to be consistant with training script. I'm not sure it will fix your issue. You may try again.
